#!/bin/bash

PLAYER=omxplayer
ERR=/dev/null

while :; do
	VID="$(wget http://74.121.151.158/pop.php -O /dev/stdout 2>$ERR)"
    if [[ -z "$VID" ]]; then
		clear
    	echo "Running default playlist" >&2
		$PLAYER -o hdmi "videos/`ls videos | shuf | head -1`" &>$ERR
    else
		VV="$(youtube-dl -e -g "$VID" 2>&1)"
		if [[ "$(echo "$VV" | grep -o ERROR)" == "ERROR" ]]; then
			clear
			echo "Error playing $(echo "$VV" | head -n 1)" >&2
		else
			clear
			echo "Playing $(echo "$VV" | head -n 1)" >&2
			$PLAYER "$(echo "$VV" | tail -n 1)" &>$ERR
		fi
    fi
done
